In [47]:
import numpy as np
import pandas as pd

In [48]:
data = pd.read_csv('Kyphosis.csv')

In [49]:
data.head()

  Kyphosis  Age  Number  Start
0   absent   71       3      5
1   absent  158       3     14
2  present  128       4      5
3   absent    2       5      1
4   absent    1       4     15

In [50]:
data.shape

(81, 4)

In [51]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Kyphosis  81 non-null     object
 1   Age       81 non-null     int64
 2   Number    81 non-null     int64
 3   Start     81 non-null     int64
dtypes: int64(3), object(1)
memory usage: 2.7+ KB

In [52]:
x = data.drop('Kyphosis',axis = 1)

In [53]:
x

    Age  Number  Start
0    71       3      5
1   158       3     14
2   128       4      5
3     2       5      1
4     1       4     15
..  ...     ...    ...
76  157       3     13
77   26       7     13
78  120       2     13
79   42       7      6
80   36       4     13

[81 rows x 3 columns]

In [54]:
y = data['Kyphosis']
y.head()

0     absent
1     absent
2    present
3     absent
4     absent
Name: Kyphosis, dtype: object

In [55]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)

In [56]:
x_train.shape

(56, 3)

In [57]:
x_test.shape

(25, 3)

In [58]:
#Decision Tree

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [59]:
pred = model.predict(x_test)
pred

In [60]:
y_test

2     present
49     absent
68     absent
78     absent
1      absent
13     absent
14     absent
66     absent
35     absent
60    present
80     absent
10    present
44     absent
75     absent
38     absent
3      absent
79    present
34     absent
24    present
76    present
50     absent
37    present
39    present
4      absent
6      absent
Name: Kyphosis, dtype: object

In [61]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)

0.64

In [62]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[15,  2],
       [ 7,  1]])

In [119]:
# Random Forest 

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators = 10)
# 'n_estimators  = 50 '   meken accuracy eka wenas karagatha haka.
model.fit(x_train,y_train)

RandomForestClassifier(n_estimators=10)

In [120]:
pred = model.predict(x_test)
pred

array(['absent', 'present', 'absent', 'present', 'absent', 'absent',
       'absent', 'absent', 'absent', 'present', 'absent', 'absent',
       'absent', 'absent', 'absent', 'absent', 'absent', 'absent',
       'absent', 'present', 'absent', 'absent', 'absent', 'absent',
       'absent'], dtype=object)

In [121]:
y_test

54     absent
58     absent
56     absent
2     present
24    present
33     absent
29     absent
23     absent
5      absent
0      absent
43     absent
8      absent
46     absent
73     absent
59     absent
55     absent
28     absent
44     absent
9     present
79    present
74     absent
11     absent
26     absent
13     absent
27     absent
Name: Kyphosis, dtype: object

In [122]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)

0.84

In [123]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[19,  2],
       [ 2,  2]])

In [124]:
data['Kyphosis'].value_counts()

Kyphosis
absent     64
present    17
Name: count, dtype: int64